server:
  httpPort: 8082 # HTTP 端口

secret: "qm-mcp-server-jwt-secret-key-2024"

database:
  mysql:
    host: ${MYSQL_SERVICE_NAME}
    port: ${MYSQL_SERVICE_PORT}
    username: ${MCP_DB_USER}
    password: ${MCP_DB_PASSWORD}
    database: ${MCP_DB_NAME}
  redis:
    host: redis-svc
    port: 6379
    password: ${REDIS_PASSWORD}
    db: 0
log:
  level: debug
  format: text

storage:
  # 存储根目录
  rootPath: /data
  # 代码包存放路径
  codePath: /data/code-package
  # static 存放路径
  staticPath: /data/static