database:
  mysql:
    host: ${MYSQL_SERVICE_NAME}
    port: ${MYSQL_SERVICE_PORT}
    username: ${MCP_DB_USER}
    password: ${MCP_DB_PASSWORD}
    database: ${MCP_DB_NAME}

log:
  level: debug
  format: text


init:
  admin_username: admin
  admin_password: admin123
  admin_nickname: admin
  admin_role_name: admin
  admin_role_description: admin role
  admin_role_level: 1
  admin_data_scope: all
