server:
  httpPort: 8081

secret: "qm-mcp-server-jwt-secret-key-2024"

domain: http://${K3S_API_URL}

services:
  mcpMarket:
    host: "mcp-market-svc"
    port: 8081
  mcpAuthz: 
    host: "mcp-authz-svc"
    port: 8082

database:
  mysql:
    host: ${MYSQL_SERVICE_NAME}
    port: ${MYSQL_SERVICE_PORT}
    username: ${MCP_DB_USER}
    password: ${MCP_DB_PASSWORD}
    database: ${MCP_DB_NAME}
  redis:
    host: redis-svc
    port: 6379
    password: ${REDIS_PASSWORD}
    db: 0

log:
  level: debug
  format: text
# 代码包存放路径
code:
  # 上传配置
  upload:
    # 单个文件最大大小 (MB)
    maxFileSize: 100
    # 允许的文件类型
    allowedExtensions: [".zip", ".tar.gz", ".tar", ".rar"]

storage:
  # 存储根目录
  rootPath: /data
  # 代码包存放路径
  codePath: /data/code-package
  # static 存放路径
  staticPath: /data/static
         