apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: mcp-web
  name: mcp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcp-web
  template:
    metadata:
      labels:
        k8s-app: mcp-web
    spec:
      containers:
        - name: mcp-web
          image: ccr.ccs.tencentyun.com/itqm-private/mcp-web:${VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-storage
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data-storage
          hostPath:
            path: ${DATA_DIR}
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-web-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    k8s-app: mcp-web

