name: Release Helm Chart

on:
  push:
    branches:
      - 'main'
      - 'v1.0.0-dev'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart 版本号'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 配置 Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: 安装 Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: 获取版本号
      id: get_version
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # 标签推送，提取版本号
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # 分支推送，从 VERSION 文件读取或生成开发版本
            if [ -f VERSION ]; then
              VERSION=$(cat VERSION)
            else
              VERSION="dev-$(date +%Y%m%d-%H%M%S)"
            fi
          fi
        else
          # 手动触发
          VERSION=${{ github.event.inputs.version }}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "发布版本: $VERSION"

    - name: 验证 Helm Chart
      run: |
        cd helm
        helm lint .
        helm template . --debug > /dev/null
        echo "✅ Helm Chart 验证通过"

    - name: 更新 Chart 版本
      run: |
        cd helm
        sed -i "s/^version:.*/version: ${{ steps.get_version.outputs.version }}/" Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: ${{ steps.get_version.outputs.version }}/" Chart.yaml
        echo "📝 Chart 版本已更新到 ${{ steps.get_version.outputs.version }}"

    - name: 运行 chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: .
        config: cr.yaml
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: 输出发布信息
      run: |
        echo "🎉 Helm Chart 发布成功!"
        echo "📦 版本: ${{ steps.get_version.outputs.version }}"
        echo "🌐 仓库地址: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "📋 Releases: https://github.com/${{ github.repository }}/releases"
        echo ""
        echo "使用以下命令添加仓库:"
        echo "helm repo add mcp-box https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "helm repo update"
        echo "helm install mcp-box mcp-box/mcp-box"